apiVersion: v1
kind: Service
metadata:
  name: deploy-minikube-service
spec:
  selector:
    app: deploy-minikube-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
